BachelorsDegreeManagement/BachelorsDegreeManagement/Controllers/StudentsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BachelorsDegreeManagement.ApplicationLogic.DataModels;
using BachelorsDegreeManagement.ApplicationLogic.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;
using BachelorsDegreeManagement.ApplicationLogic.ViewModels;
using System;

namespace BachelorsDegreeManagement.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IStudentsService _studentService;
        private readonly IGroupsService _groupsService;
        private readonly IDeadlinesService _deadlinesService;
        private readonly IProfessorsService _professorsService;
        private readonly IOptionsFactoryService _optionsFactoryService;
        private readonly IUsersService _usersService;
        private readonly IProjectsService _projectsService;
        private readonly IPersonalityTestResultsService _testService;
        private readonly IExportService _exportService;

        public StudentsController(ILoggerManager logger, IStudentsService studentsService, IGroupsService groupsService,
            IDeadlinesService deadlinesService, IProfessorsService professorsService, IOptionsFactoryService optionsFactoryService,
            IUsersService usersService, IProjectsService projectsService, IPersonalityTestResultsService testService,
            IExportService exportService)
        {
            _logger = logger;
            _studentService = studentsService;
            _groupsService = groupsService;
            _deadlinesService = deadlinesService;
            _professorsService = professorsService;
            _optionsFactoryService = optionsFactoryService;
            _usersService = usersService;
            _projectsService = projectsService;
            _testService = testService;
            _exportService = exportService;
        }

        [Authorize(Roles = "Student")]
        public async Task<IActionResult> Dashboard()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            if (_deadlinesService.GetNextDeadline() != null)
            {
                ViewData["deadlines"] = 1;
                ViewData["options"] = (await _optionsFactoryService.FindSentCustomOptions(user)).Count() +
                (await _optionsFactoryService.FindSentOptions(user)).Count();
                ViewData["professors"] = (await _professorsService.GetProfessors()).Count();
                ViewData["projects"] = (await _projectsService.GetAllProjects()).Count();
            }

            return View();
        }

        // GET: Students
        [Authorize]
        public async Task<IActionResult> Index()
        {
            StudentsIndexViewModel model = new StudentsIndexViewModel
            {
                Students = await _studentService.GetStudents(),
                ImportViewModel = new StudentsImportViewModel()
            };
            return View(model);
        }

        // GET: Students/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _studentService.GetStudent(id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create()
        {
            ViewData["GroupId"] = new SelectList(await _groupsService.GetGroups(), "Id", "Name");

            return View();
        }

        // POST: Students/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("GDPRCode,FirstName,LastName,GroupId,Grade")] Students student)
        {
            if (ModelState.IsValid)
            {
                var result = _studentService.CreateStudent(student);
                if (result)
                {
                    ViewData["success"] = "The student has been registered.";
                }
                else
                {
                    ViewData["error"] = "The student already exists";
                }
            }
            else
            {
                ViewData["error"] = "The data was not valid.";
            }

            ViewData["GroupId"] = new SelectList(await _groupsService.GetGroups(), "Id", "Name");
            return View(student);
        }

        // GET: Students/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _studentService.GetStudent(id);
            if (students == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = new SelectList(await _groupsService.GetGroups(), "Id", "Name");
            return View(students);
        }

        // POST: Students/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(string id, [Bind("GDPRCode,FirstName,LastName,GroupId,Grade")] Students students)
        {
            if (id != students.GDPRCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _studentService.UpdateStudent(students);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await StudentsExists(students.GDPRCode)))
                    {
                        _logger.LogInfo("The student " + students.GDPRCode +" does not exist");
                        return NotFound();
                    }
                    else
                    {
                        _logger.LogError("Student update error");
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GroupId"] = new SelectList(await _groupsService.GetGroups(), "Id", "Name");
            return View(students);
        }

        // GET: Students/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _studentService.GetStudent(id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var student = await _studentService.GetStudent(id);
            if(student != null && student.UserId == null)
            {
                // delete only the students that do not have an account
                _studentService.DeleteStudent(student);
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        private async Task<bool> StudentsExists(string id)
        {
            return await _studentService.GetStudent(id) != null;
        }

        [Authorize(Roles = "Professor")]
        // GET: Students/Suggestions
        [HttpGet]
        public async Task<IActionResult> Suggestions()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            bool valid = await _testService.CheckPersonalityTest(user);
            if (valid)
            {
                var suggestedStudents = await _studentService.FindSuggestedStudents(user);
                return View(suggestedStudents);
            }
            else
            {
                return RedirectToAction("Create", "PersonalityTestResults");
            }
            
        }

        [Authorize(Roles ="Administrator")]
        [HttpPost]
        public async Task<IActionResult> Import(StudentsImportViewModel model) 
        {
            if(model.Document != null&& model.Document.ContentType.Equals("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))
            {
                try
                {
                    await _studentService.Import(model);
                    return RedirectToAction(nameof(Index));
                }catch(Exception e)
                {
                    _logger.LogInfo("The excel file did not use the standard layout");
                }
                
            }
            else
            {
                _logger.LogWarn("The admin did not upload the file");
                ViewData["error"] = "You need to upload an Excel file";
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public async Task<IActionResult> Export()
        {
            _exportService.SetFilePath("\\documents\\export\\students.csv");
            var path = await _exportService.ExportData();

            return Json(path);
        }
    }
}

BachelorsDegreeManagement/BachelorsDegreeManagement/Controllers/UserTagsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BachelorsDegreeManagement.ApplicationLogic.DataModels;
using BachelorsDegreeManagement.ApplicationLogic.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;

namespace BachelorsDegreeManagement.Controllers
{
    public class UserTagsController : Controller
    {
        private readonly ITagsService _tagsService;
        private readonly IUsersService _usersService;
        private readonly IUserTagsService _usersTagsService;

        public UserTagsController( ITagsService tagsService,
            IUsersService usersService, IUserTagsService userTagsService)
        {
            _tagsService = tagsService;
            _usersService = usersService;
            _usersTagsService = userTagsService;
        }

        // GET: UserTags/Index/UserId
        [Authorize]
        public async Task<IActionResult> Index(string id)
        {
            Users user = null;
            if(id == null)
            {
                user = await _usersService.GetCurrentUser(HttpContext.User);
            }
            else
            {
                user = await _usersService.GetUser(id);
            }
            
            var tags = _tagsService.GetUsersTags(user);
            var models = _tagsService.GetTagModels(tags);
            ViewData["user"] = user;
            return View(models);
        }

        // GET: UserTags/Create
        [Authorize(Roles="Professor, Student")]
        public async Task<IActionResult> Create()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            ViewData["TagId"] = new SelectList(_tagsService.GetAvailableTags(user), "Id", "Name");
            return View();
        }

        // POST: UserTags/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Professor, Student")]
        public async Task<IActionResult> Create([Bind("TagId")] UserTags userTags)
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            if (ModelState.IsValid)
            {
                userTags.UserId = user.Id;
                _usersTagsService.AddUserTag(userTags);
                ViewData["success"] = "The tag was added into your list.";
            }
            else
            {
                ViewData["error"] = "The data is not valid";
            }
            ViewData["TagId"] = new SelectList(_tagsService.GetAvailableTags(user), "Id", "Name");
            return View(userTags);
        }
    }
}

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Students/Create.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.DataModels.Students

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-5 col-xl-5 col-lg-5 jumbotron">
        <h4>Add a student</h4>
        <hr />
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GDPRCode" class="control-label"></label>
                <input asp-for="GDPRCode" class="form-control" />
                <span asp-validation-for="GDPRCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <select asp-for="GroupId" class="form-control" asp-items="ViewBag.GroupId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="submit-button" />
            </div>
        </form>
    </div>
</div>

<div id="back-button">
    <a class="btn btn-outline-secondary" asp-action="Index"><i class="fas fa-chevron-left"></i> See list</a>
    <img src="~/images/svgs/single-eye-bean-outline.svg" alt="back-button-bean" id="back-button-bean" />
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Students/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@*<h1>Welcome back!</h1>*@

<div class="row justify-content-center">
    <div class="col-md-10 row justify-content-around jumbotron row justify-content-center">
        <div class="row justify-content-center col-12 col-md-4 col-lg-4 col-xl-4 border-right">
            <div class="container-title col-12 border-bottom">
                <h3 class="col-12">System information</h3>
            </div>
            <div class="container-content col-12 border-bottom">
                @if(ViewData["deadlines"] == null){
                <p>There is no deadline active.</p>

                }else{
                <p>There is an active deadline.</p>

                }
                <p>There are @ViewData["projects"] projects into the system.</p>
                <p>There are @ViewData["professors"] professors into the system.</p>
                <p>You have sent @ViewData["options"] options.</p>
            </div>
            <div class="container-deadline col-12 border-bottom">
                <h4 id="deadline-title"></h4>
                <p id="deadline-description"></p>
            </div>
        </div>
        <div class="col-12 col-md-8 col-lg-8 col-xl-8">
            <div class="calendar"></div>
        </div>
    </div>
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Students/Delete.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.DataModels.Students

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-5 col-xl-5 col-lg-5 jumbotron">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <hr />
            <dl class="row">
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.LastName)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Grade)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Grade)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.User.Email)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.User.Email)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Group)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Group.Name)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="GDPRCode" />
                <input type="submit" value="Delete" class="btn btn-outline-danger" id="submit-button" />
            </form>
        </div>
    </div>
</div>

<div id="back-button">
    <a class="btn btn-outline-secondary" asp-action="Index"><i class="fas fa-chevron-left"></i> See list</a>
    <img src="~/images/svgs/single-eye-bean-outline.svg" alt="back-button-bean" id="back-button-bean" />
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Students/Details.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.DataModels.Students

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-5 col-xl-5 col-lg-5 jumbotron">
        <h4>See a student's details</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Grade)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Grade)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.User.Email)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.User.Email)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Group)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Group.Name)
            </dd>
        </dl>
    </div>
</div>

<div id="back-button">
    <a class="btn btn-outline-secondary" asp-action="Index"><i class="fas fa-chevron-left"></i> See list</a>
    <img src="~/images/svgs/single-eye-bean-outline.svg" alt="back-button-bean" id="back-button-bean" />
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Students/Edit.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.DataModels.Students

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-5 col-xl-5 col-lg-5 jumbotron">
        <h4>Edit a student's information</h4>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GDPRCode" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <select asp-for="GroupId" class="form-control" asp-items="ViewBag.GroupId"></select>
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" id="submit-button" />
            </div>
        </form>
    </div>
</div>

<div id="back-button">
    <a class="btn btn-outline-secondary" asp-action="Index"><i class="fas fa-chevron-left"></i> See list</a>
    <img src="~/images/svgs/single-eye-bean-outline.svg" alt="back-button-bean" id="back-button-bean" />
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Students/Index.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.ViewModels.StudentsIndexViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="jumbotron row justify-content-center col-11 col-md-10 col-lg-10 col-xl-10">
        <div class="col-12 col-xl-10 col-lg-10 col-md-10">
            <h3>The students:</h3>
            <br />
        </div>
        @if (User.IsInRole("Administrator"))
        {
            @await Html.PartialAsync("StudentsImportModal", Model.ImportViewModel)

            <div class="col-10 row justify-content-start">
                <p class="col-12 col-md-auto col-xl-auto col-lg-auto">
                    <a asp-action="Create" data-toggle="tooltip" data-placement="bottom" title="Add a new student"><i class="fas fa-plus-circle"></i></a>
                </p>
                <p class="col-12 col-md-auto col-xl-auto col-lg-auto">
                    <a data-toggle="tooltip" href="#" data-placement="bottom" title="Import" id="import-modal-trigger"><i class="fas fa-cloud-upload-alt"></i></a>
                </p>
                <p class="col-12 col-md-auto col-xl-auto col-lg-auto">
                    <a data-toggle="tooltip" href="#" data-placement="bottom" title="Export" id="export-students"><i class="fas fa-cloud-download-alt"></i></a>
                </p>
            </div>
        }
        <div class="col-12 col-xl-12 col-lg-12 col-md-12 table-responsive">
            <table class="display compact" style="width:100%; position: relative" id="studentsTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Students.First().FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Students.First().LastName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Students.First().Grade)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Students.First().User.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Students.First().Group)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Students.First().Group.Specialization.Acronym)
                        </th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Students)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Grade)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Group.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Group.Specialization.Acronym)
                            </td>
                            <td>
                                @if (item.UserId != null)
                                {
                                    <a asp-controller="UserTags" asp-action="Index" asp-route-id="@item.UserId"><i class="fas fa-tag"></i></a>
                                }
                                <a asp-controller="Students" asp-action="Details" asp-route-id="@item.GDPRCode"><i class="fas fa-info"></i></a>

                                @if (User.IsInRole("Administrator"))
                                {
                                    <a asp-controller="Students" asp-action="Edit" asp-route-id="@item.GDPRCode"><i class="fas fa-edit"></i></a>
                                    <a asp-controller="Students" asp-action="Delete" asp-route-id="@item.GDPRCode"><i class="fas fa-trash"></i></a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Students/Suggestions.cshtml
@model IEnumerable<BachelorsDegreeManagement.ApplicationLogic.ViewModels.GetStudentsSuggestionsViewModel>

@{
    ViewData["Title"] = "Suggestions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="jumbotron row justify-content-center col-11 col-md-10 col-lg-10 col-xl-10">
        <div class="col-12 col-xl-12 col-lg-12 col-md-12 table-responsive">
            <br />
            <h3>The students:</h3>
            <hr />
            <br />
            <table class="display" style="width:100%; position: relative" id="professorsTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Student.FullName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Student.User.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Student.Grade)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TagsScore)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PersonalityScore)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SupervisorStyleScore)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CompatibilityScore)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.User.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.Grade)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TagsScore)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PersonalityScore)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SupervisorStyleScore)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CompatibilityScore)
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <br />
        </div>
    </div>
</div>