BachelorsDegreeManagement/BachelorsDegreeManagement/Controllers/ProfessorsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BachelorsDegreeManagement.ApplicationLogic.DataModels;
using Microsoft.AspNetCore.Authorization;
using BachelorsDegreeManagement.ApplicationLogic.Services.Abstractions;
using BachelorsDegreeManagement.ApplicationLogic.ViewModels;
using System;
using BachelorsDegreeManagement.ApplicationLogic.Services;

namespace BachelorsDegreeManagement.Controllers
{
    public class ProfessorsController : Controller
    {
        private readonly IUsersService _usersService;
        private readonly IProfessorsService _professorsService;
        private readonly IDepartmentsService _departmentsService;
        private readonly IStudentsService _studentsService;
        private readonly IDeadlinesService _deadlinesService;
        private readonly IOptionsFactoryService _optionsFactoryService;
        private readonly IProjectsService _projectsService;
        private readonly IPersonalityTestResultsService _testService;
        private readonly ILoggerManager _logger;
        private readonly IExportService _exportService;

        public ProfessorsController(IUsersService usersService, IProjectsService projectsService,
            IProfessorsService professorsService, IDepartmentsService departmentsService,
            IStudentsService studentsService, IDeadlinesService deadlinesService, IOptionsFactoryService optionsFactoryService,
            IPersonalityTestResultsService testResultsService, ILoggerManager logger, IExportService exportService)
        {
            this._usersService = usersService;
            this._professorsService = professorsService;
            this._departmentsService = departmentsService;
            this._studentsService = studentsService;
            this._deadlinesService = deadlinesService;
            this._optionsFactoryService = optionsFactoryService;
            this._projectsService = projectsService;
            this._testService = testResultsService;
            this._logger = logger;
            this._exportService = exportService;
        }

        [Authorize(Roles = "Professor")]
        public async Task<IActionResult> Dashboard()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            if (_deadlinesService.GetNextDeadline() != null)
            {
                ViewData["deadlines"] = 1;
            }
            ViewData["options"] = (await _optionsFactoryService.FindReceivedCustomOptions(user)).Count() + 
                (await _optionsFactoryService.FindReceivedOptions(user)).Count();
            ViewData["students"] = (await _studentsService.GetStudents()).Count();
            ViewData["projects"] = (await _projectsService.GetProjectsWithMinimalInfo(user)).Count();
            return View();
        }

        [Authorize(Roles = "Student")]
        // GET: Professors/Suggestions
        [HttpGet]
        public async Task<IActionResult> Suggestions()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            bool valid = await _testService.CheckPersonalityTest(user);
            if (valid)
            {
                var suggestedProfessors = await _professorsService.FindSuggestedProfessors(user);
                return View(suggestedProfessors);
            }
            else
            {
                return RedirectToAction("Create", "PersonalityTestResults");
            }
            
        }

        // GET: Professors
        [Authorize]
        public async Task<IActionResult> Index()
        {
            ProfessorsIndexViewModel model = new ProfessorsIndexViewModel
            {
                Professors = User.IsInRole("Administrator") ? await _professorsService.GetRegisteredProfessors() : await _professorsService.GetProfessors(),
                ImportViewModel = new ProfessorsImportViewModel()
            };
            return View(model);
        }

        // GET: Professors/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var professor = await _professorsService.GetProfessor(id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        // GET: Professors/Create
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create()
        {
            ViewData["DepartmentId"] = new SelectList(await _departmentsService.GetDepartments(), "Id", "Name");
            return View();
        }

        // POST: Professors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("GDPRCode,FirstName,LastName,DepartmentId,ProjectsNumber")] Professors professor)
        {
            if (ModelState.IsValid)
            {
                var result = _professorsService.AddProfessor(professor);
                if (result)
                {
                    ViewData["success"] = "The professor has been registered.";
                }
                else
                {
                    ViewData["error"] = "The professor already exists";
                }
            }
            else
            {
                ViewData["error"] = "The data is not valid.";
            }
            ViewData["DepartmentId"] = new SelectList(await _departmentsService.GetDepartments(), "Id", "Name", professor.DepartmentId);
            return View(professor);
        }

        // GET: Professors/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var professor = await _professorsService.GetProfessor(id);
            if (professor == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(await _departmentsService.GetDepartments(), "Id", "Name", professor.DepartmentId);
            return View(professor);
        }

        // POST: Professors/Edit/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("GDPRCode,FirstName,LastName,DepartmentId,ProjectsNumber")] Professors professor)
        {   
            if (ModelState.IsValid)
            {
                try
                {
                    _professorsService.UpdateProfessor(professor);
                    ViewData["success"] = "The professor's details have been updated.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await ProfessorsExists(professor.GDPRCode)))
                    {
                        ViewData["error"] = "Something wrong happend.";
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            ViewData["DepartmentId"] = new SelectList(await _departmentsService.GetDepartments(), "Id", "Name", professor.DepartmentId);
            return View(professor);
        }

        // GET: Professors/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var professor = await _professorsService.GetProfessor(id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        // POST: Professors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var professor = await _professorsService.GetProfessor(id);
            if( professor != null && professor.UserId == null)
            {
                await _professorsService.DeleteProfessor(professor);
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        private async Task<bool> ProfessorsExists(string id)
        {
            return (await _professorsService.GetProfessor(id)) != null;
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Import(ProfessorsImportViewModel model)
        {
            if (model.Document != null && model.Document.ContentType.Equals("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))
            {
                try
                {
                    await _professorsService.Import(model);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    _logger.LogInfo("The excel file did not use the standard layout");
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public async Task<IActionResult> Export()
        {
            _exportService.SetFilePath("\\documents\\export\\professors.csv");
            var path = await _exportService.ExportData(false);

            return Json(path);
        }
    }
}

BachelorsDegreeManagement/BachelorsDegreeManagement/Controllers/UserTagsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BachelorsDegreeManagement.ApplicationLogic.DataModels;
using BachelorsDegreeManagement.ApplicationLogic.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;

namespace BachelorsDegreeManagement.Controllers
{
    public class UserTagsController : Controller
    {
        private readonly ITagsService _tagsService;
        private readonly IUsersService _usersService;
        private readonly IUserTagsService _usersTagsService;

        public UserTagsController( ITagsService tagsService,
            IUsersService usersService, IUserTagsService userTagsService)
        {
            _tagsService = tagsService;
            _usersService = usersService;
            _usersTagsService = userTagsService;
        }

        // GET: UserTags/Index/UserId
        [Authorize]
        public async Task<IActionResult> Index(string id)
        {
            Users user = null;
            if(id == null)
            {
                user = await _usersService.GetCurrentUser(HttpContext.User);
            }
            else
            {
                user = await _usersService.GetUser(id);
            }
            
            var tags = _tagsService.GetUsersTags(user);
            var models = _tagsService.GetTagModels(tags);
            ViewData["user"] = user;
            return View(models);
        }

        // GET: UserTags/Create
        [Authorize(Roles="Professor, Student")]
        public async Task<IActionResult> Create()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            ViewData["TagId"] = new SelectList(_tagsService.GetAvailableTags(user), "Id", "Name");
            return View();
        }

        // POST: UserTags/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Professor, Student")]
        public async Task<IActionResult> Create([Bind("TagId")] UserTags userTags)
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            if (ModelState.IsValid)
            {
                userTags.UserId = user.Id;
                _usersTagsService.AddUserTag(userTags);
                ViewData["success"] = "The tag was added into your list.";
            }
            else
            {
                ViewData["error"] = "The data is not valid";
            }
            ViewData["TagId"] = new SelectList(_tagsService.GetAvailableTags(user), "Id", "Name");
            return View(userTags);
        }
    }
}

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Professors/Create.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.DataModels.Professors

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-5 col-xl-5 col-lg-5 jumbotron">
        <h4>Add a new professor</h4>
        <hr />
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GDPRCode" class="control-label"></label>
                <input asp-for="GDPRCode" class="form-control" />
                <span asp-validation-for="GDPRCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProjectsNumber" class="control-label"></label>
                <input asp-for="ProjectsNumber" class="form-control" />
                <span asp-validation-for="ProjectsNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="submit-button" />
            </div>
        </form>
    </div>
</div>

<div id="back-button">
    <a class="btn btn-outline-secondary" asp-controller="Professors" asp-action="Index"><i class="fas fa-chevron-left"></i> See list</a>
    <img src="~/images/svgs/single-eye-bean-outline.svg" alt="back-button-bean" id="back-button-bean" />
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Professors/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@*<h1>Welcome back!</h1>*@

<div class="row justify-content-center">
    <div class="col-md-10 row justify-content-around jumbotron row justify-content-center">
        <div class="row justify-content-center col-12 col-md-4 col-lg-4 col-xl-4 border-right">
            <div class="container-title col-12 border-bottom">
                <h3 class="col-12">System information</h3>
            </div>
            <div class="container-content col-12 border-bottom">
                @if(ViewData["deadlines"] == null){
                <p>There is no deadline active.</p>

                }else{
                <p>There is an active deadline.</p>

                }
                <p>The number of projects that have been proposed by you: @ViewData["projects"].</p>
                <p>There are @ViewData["students"] students into the system.</p>
                <p>You have received @ViewData["options"] options.</p>
            </div>
            <div class="container-deadline col-12 border-bottom">
                <h4 id="deadline-title"></h4>
                <p id="deadline-description"></p>
            </div>
        </div>
        <div class="col-12 col-md-8 col-lg-8 col-xl-8">
            <div class="calendar"></div>
        </div>
    </div>
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Professors/Delete.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.DataModels.Professors

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-5 col-xl-5 col-lg-5 jumbotron">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Professors</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.LastName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProjectsNumber)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ProjectsNumber)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.User.Email)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.User.Email)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Department)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Department.Name)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="GDPRCode" />
                <input type="submit" value="Delete" class="btn btn-outline-danger" id="submit-button" />
            </form>
        </div>
    </div>
</div>

<div id="back-button">
    <a class="btn btn-outline-secondary" asp-controller="Professors" asp-action="Index"><i class="fas fa-chevron-left"></i> See list</a>
    <img src="~/images/svgs/single-eye-bean-outline.svg" alt="back-button-bean" id="back-button-bean" />
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Professors/Details.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.DataModels.Professors

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-5 col-xl-5 col-lg-5 jumbotron">
        <h4>See a professor's details</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.ProjectsNumber)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.ProjectsNumber)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.User.Email)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.User.Email)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Department)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Department.Name)
            </dd>
        </dl>
    </div>
</div>

<div id="back-button">
    <a class="btn btn-outline-secondary" asp-controller="Professors" asp-action="Index"><i class="fas fa-chevron-left"></i> See list</a>
    <img src="~/images/svgs/single-eye-bean-outline.svg" alt="back-button-bean" id="back-button-bean" />
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Professors/Edit.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.DataModels.Professors

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-5 col-xl-5 col-lg-5 jumbotron">
        <h4>Edit a professor's information</h4>
        <hr />
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GDPRCode" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectsNumber" class="control-label"></label>
                <input asp-for="ProjectsNumber" class="form-control" />
                <span asp-validation-for="ProjectsNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" id="submit-button" />
            </div>
        </form>
    </div>
</div>

<div id="back-button">
    <a class="btn btn-outline-secondary" asp-controller="Professors" asp-action="Index"><i class="fas fa-chevron-left"></i> See list</a>
    <img src="~/images/svgs/single-eye-bean-outline.svg" alt="back-button-bean" id="back-button-bean" />
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Professors/Index.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.ViewModels.ProfessorsIndexViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row justify-content-center">
    <div class="jumbotron row justify-content-center col-11 col-md-10 col-lg-10 col-xl-10">
        <div class="col-12 col-xl-10 col-lg-10 col-md-10">
            <h3>The professors:</h3>
            <br />
        </div>
        @if (User.IsInRole("Administrator"))
        {
            @await Html.PartialAsync("ProfessorsImportModal", Model.ImportViewModel)
            <div class="col-10 row justify-content-start">
                <p class="col-12 col-md-auto col-xl-auto col-lg-auto">
                    <a asp-action="Create" data-toggle="tooltip" data-placement="bottom" title="Add a new professor"><i class="fas fa-plus-circle"></i></a>
                </p>
                <p class="col-12 col-md-auto col-xl-auto col-lg-auto">
                    <a data-toggle="tooltip" href="#" data-placement="bottom" title="Import" id="professors-import-modal-trigger"><i class="fas fa-cloud-upload-alt"></i></a>
                </p>
                <p class="col-12 col-md-auto col-xl-auto col-lg-auto">
                    <a data-toggle="tooltip" href="#" data-placement="bottom" title="Export" id="export-supervisors"><i class="fas fa-cloud-download-alt"></i></a>
                </p>
            </div>
        }
        <div class="col-12 col-xl-12 col-lg-12 col-md-12 table-responsive">
            <table class="display compact" style="width:100%; position: relative" id="professorsTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Professors.First().FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Professors.First().LastName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Professors.First().ProjectsNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Professors.First().User.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Professors.First().User.PhoneNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Professors.First().Department.Name)
                        </th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Professors)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProjectsNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.PhoneNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Department.Name)
                            </td>
                            <td>
                                @if (item.UserId != null)
                                {

                                    <a asp-controller="UserTags" asp-action="Index" asp-route-id="@item.UserId"><i class="fas fa-tag"></i></a>

                                }
                                <a asp-controller="Professors" asp-action="Details" asp-route-id="@item.GDPRCode"><i class="fas fa-info"></i></a>

                                @if (User.IsInRole("Administrator"))
                                {
                                    <a asp-controller="Professors" asp-action="Edit" asp-route-id="@item.GDPRCode"><i class="fas fa-edit"></i></a>
                                    <a asp-controller="Professors" asp-action="Delete" asp-route-id="@item.GDPRCode"><i class="fas fa-trash"></i></a>

                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
        </div>
    </div>
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Professors/Suggestions.cshtml
@model IEnumerable<BachelorsDegreeManagement.ApplicationLogic.ViewModels.GetSuggestionsViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="jumbotron row justify-content-center col-11 col-md-10 col-lg-10 col-xl-10">
        <div class="col-12 col-xl-12 col-lg-12 col-md-12 table-responsive">
            <br />
            <h3>The professors:</h3>
            <hr />
            <br />
            <table class="display" style="width:100%; position: relative" id="professorsTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Professor.FullName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Professor.User.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TagsScore)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PersonalityScore)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SupervisorStyleScore)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CompatibilityScore)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Professor.FullName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Professor.User.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TagsScore)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PersonalityScore)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SupervisorStyleScore)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CompatibilityScore)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
        </div>
    </div>
</div>