BachelorsDegreeManagement/BachelorsDegreeManagement/Controllers/ProjectsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BachelorsDegreeManagement.ApplicationLogic.DataModels;
using BachelorsDegreeManagement.ApplicationLogic.Services.Abstractions;
using BachelorsDegreeManagement.ApplicationLogic.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace BachelorsDegreeManagement.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IProjectsService _projectsService;
        private readonly IUsersService _usersService;
        private readonly ITagsService _tagsService;
        private readonly ISystemVariablesService _variablesService;
        private readonly IProfessorsService _professorsService;
        private readonly UserManager<Users> _userManager;
        private readonly IPersonalityTestResultsService _testService;

        public ProjectsController(
            IProjectsService projectsService,
            IUsersService usersService,
            ITagsService tagsService,
            ISystemVariablesService variablesService,
            IProfessorsService professorsService,
            UserManager<Users> userManager,
            IPersonalityTestResultsService testResultsService)
        {
            _projectsService = projectsService;
            _usersService = usersService;
            _tagsService = tagsService;
            _variablesService = variablesService;
            _userManager = userManager;
            _professorsService = professorsService;
            _testService = testResultsService;
        }

        [Authorize(Roles = "Professor, Student")]
        // GET: Projects
        public async Task<IActionResult> Index()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            var role = (await _userManager.GetRolesAsync(user))[0];
            if (role.Equals("Professor"))
            {
                var projects = await _projectsService.GetProjects(user);
                var projectsViewModel = await _projectsService.GetProjectsViewModelList(projects, user, true);
                return View(projectsViewModel);
            }
            else
            {
                bool valid = await _testService.CheckPersonalityTest(user);
                if (valid)
                {
                    var projects = await _projectsService.GetAllProjects();
                    var projectsViewModel = await _projectsService.GetProjectsViewModelList(projects, user, false);

                    return View(projectsViewModel);
                }
                else
                {
                    return RedirectToAction("Create", "PersonalityTestResults");
                }
               
            }
        }

        [Authorize]
        public async Task<IActionResult> GetProjects(string id)
        {
            var user = await _usersService.GetUser(id);
            var projects = await _projectsService.GetProjectsWithMinimalInfo(user);
            return Json(projects);
        }

        [Authorize(Roles = "Professor, Student")]
        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var project = await _projectsService.GetProject(id);
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            var role = (await _userManager.GetRolesAsync(user))[0];
            bool isProfessor = role.Equals("Professor");
            var model = await _projectsService.GetProjectViewModel(project, user, isProfessor);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [Authorize(Roles = "Professor")]
        // GET: Projects/Create
        public async Task<IActionResult> Create()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            CreateProjectViewModel model = new CreateProjectViewModel();

            var tags = _tagsService.GetUsersTags(user);
            var complexities = _variablesService.GetVariableLikeName("complexityLevel");
            if (tags == null || tags.Count == 0)
            {
                // redirect to the functionality used to add a tag into the user's list
                return RedirectToAction("Create", "UserTags");
            }
            else
            {
                // the users have tags in their list, so they can add a project
                ViewData["Tags"] = new SelectList(tags, "Name", "Name");
                ViewData["Complexities"] = new SelectList(complexities, "Value", "Value");
                return View(model);
            } 
        }

        // POST: Projects/Create
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProjectViewModel model)
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            
            if (_projectsService.CheckDeadline())
            {
                if (ModelState.IsValid && !model.Complexity.Equals("Choose the project complexity"))
                {
                    if (await _professorsService.CheckAvailability(user))
                    {
                        _projectsService.AddProject(model, user);
                        ViewData["success"] = "The project has been successfully added";
                    }
                    else
                    {
                        ViewData["error"] = "You are not available anymore...";
                    }
                }
                else
                {
                    ViewData["error"] = "The data is invalid";
                }
            }
            else
            {
                ViewData["error"] = "Too late, the deadline has passed...";
            }

            var tags = _tagsService.GetUsersTags(user);
            ViewData["Tags"] = new SelectList(tags, "Name", "Name");
            var complexities = _variablesService.GetVariableLikeName("complexityLevel");
            ViewData["Complexities"] = new SelectList(complexities, "Value", "Value");
            return View(model);
        }

        [Authorize(Roles = "Professor")]
        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _projectsService.GetProject(id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }


        [Authorize(Roles = "Professor")]
        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_projectsService.CheckDeadline())
            {
                var project = await _projectsService.GetProject(id);
                _projectsService.DeleteProject(project);
                return RedirectToAction(nameof(Index));
            }
            else {
                ViewData["error"] = "It is too late to perform this action";
                return View();
            }
        }

        [Authorize]
        private async Task<bool> ProjectsExists(int id)
        {
            return (await _projectsService.GetProject(id)) != null;
        }
    }
}

BachelorsDegreeManagement/BachelorsDegreeManagement/Controllers/StudentsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BachelorsDegreeManagement.ApplicationLogic.DataModels;
using BachelorsDegreeManagement.ApplicationLogic.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;
using BachelorsDegreeManagement.ApplicationLogic.ViewModels;
using System;

namespace BachelorsDegreeManagement.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IStudentsService _studentService;
        private readonly IGroupsService _groupsService;
        private readonly IDeadlinesService _deadlinesService;
        private readonly IProfessorsService _professorsService;
        private readonly IOptionsFactoryService _optionsFactoryService;
        private readonly IUsersService _usersService;
        private readonly IProjectsService _projectsService;
        private readonly IPersonalityTestResultsService _testService;
        private readonly IExportService _exportService;

        public StudentsController(ILoggerManager logger, IStudentsService studentsService, IGroupsService groupsService,
            IDeadlinesService deadlinesService, IProfessorsService professorsService, IOptionsFactoryService optionsFactoryService,
            IUsersService usersService, IProjectsService projectsService, IPersonalityTestResultsService testService,
            IExportService exportService)
        {
            _logger = logger;
            _studentService = studentsService;
            _groupsService = groupsService;
            _deadlinesService = deadlinesService;
            _professorsService = professorsService;
            _optionsFactoryService = optionsFactoryService;
            _usersService = usersService;
            _projectsService = projectsService;
            _testService = testService;
            _exportService = exportService;
        }

        [Authorize(Roles = "Student")]
        public async Task<IActionResult> Dashboard()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            if (_deadlinesService.GetNextDeadline() != null)
            {
                ViewData["deadlines"] = 1;
                ViewData["options"] = (await _optionsFactoryService.FindSentCustomOptions(user)).Count() +
                (await _optionsFactoryService.FindSentOptions(user)).Count();
                ViewData["professors"] = (await _professorsService.GetProfessors()).Count();
                ViewData["projects"] = (await _projectsService.GetAllProjects()).Count();
            }

            return View();
        }

        // GET: Students
        [Authorize]
        public async Task<IActionResult> Index()
        {
            StudentsIndexViewModel model = new StudentsIndexViewModel
            {
                Students = await _studentService.GetStudents(),
                ImportViewModel = new StudentsImportViewModel()
            };
            return View(model);
        }

        // GET: Students/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _studentService.GetStudent(id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create()
        {
            ViewData["GroupId"] = new SelectList(await _groupsService.GetGroups(), "Id", "Name");

            return View();
        }

        // POST: Students/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("GDPRCode,FirstName,LastName,GroupId,Grade")] Students student)
        {
            if (ModelState.IsValid)
            {
                var result = _studentService.CreateStudent(student);
                if (result)
                {
                    ViewData["success"] = "The student has been registered.";
                }
                else
                {
                    ViewData["error"] = "The student already exists";
                }
            }
            else
            {
                ViewData["error"] = "The data was not valid.";
            }

            ViewData["GroupId"] = new SelectList(await _groupsService.GetGroups(), "Id", "Name");
            return View(student);
        }

        // GET: Students/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _studentService.GetStudent(id);
            if (students == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = new SelectList(await _groupsService.GetGroups(), "Id", "Name");
            return View(students);
        }

        // POST: Students/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(string id, [Bind("GDPRCode,FirstName,LastName,GroupId,Grade")] Students students)
        {
            if (id != students.GDPRCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _studentService.UpdateStudent(students);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await StudentsExists(students.GDPRCode)))
                    {
                        _logger.LogInfo("The student " + students.GDPRCode +" does not exist");
                        return NotFound();
                    }
                    else
                    {
                        _logger.LogError("Student update error");
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GroupId"] = new SelectList(await _groupsService.GetGroups(), "Id", "Name");
            return View(students);
        }

        // GET: Students/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _studentService.GetStudent(id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var student = await _studentService.GetStudent(id);
            if(student != null && student.UserId == null)
            {
                // delete only the students that do not have an account
                _studentService.DeleteStudent(student);
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        private async Task<bool> StudentsExists(string id)
        {
            return await _studentService.GetStudent(id) != null;
        }

        [Authorize(Roles = "Professor")]
        // GET: Students/Suggestions
        [HttpGet]
        public async Task<IActionResult> Suggestions()
        {
            var user = await _usersService.GetCurrentUser(HttpContext.User);
            bool valid = await _testService.CheckPersonalityTest(user);
            if (valid)
            {
                var suggestedStudents = await _studentService.FindSuggestedStudents(user);
                return View(suggestedStudents);
            }
            else
            {
                return RedirectToAction("Create", "PersonalityTestResults");
            }
            
        }

        [Authorize(Roles ="Administrator")]
        [HttpPost]
        public async Task<IActionResult> Import(StudentsImportViewModel model) 
        {
            if(model.Document != null&& model.Document.ContentType.Equals("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))
            {
                try
                {
                    await _studentService.Import(model);
                    return RedirectToAction(nameof(Index));
                }catch(Exception e)
                {
                    _logger.LogInfo("The excel file did not use the standard layout");
                }
                
            }
            else
            {
                _logger.LogWarn("The admin did not upload the file");
                ViewData["error"] = "You need to upload an Excel file";
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public async Task<IActionResult> Export()
        {
            _exportService.SetFilePath("\\documents\\export\\students.csv");
            var path = await _exportService.ExportData();

            return Json(path);
        }
    }
}

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Shared/ProfessorsImportModal.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.ViewModels.ProfessorsImportViewModel

<div class="col-12" id="professors-import-dialog" style="display: none;">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-10 col-xl-10">
            <h3 class="page-title">Import professors</h3>
            <hr />
            <form asp-controller="Professors" asp-action="Import" enctype="multipart/form-data" class="row">
                <div class="form-group col-12 col-md-6 col-lg-6 col-xl-6">
                    <label asp-for="Document">Upload the file</label>
                    <input asp-for="Document" class="form-control-file" type="file" style="width:100%;" />
                </div>
                <hr />
                <div class="form-group button-modal col-12">
                    <input type="submit" value="Start the import process" id="import-submit-button" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Shared/StudentsImportModal.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.ViewModels.StudentsImportViewModel

<div class="col-12" id="students-import-dialog" style="display: none;">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-10 col-xl-10">
            <h3 class="page-title">Import students</h3>
            <hr />
            <form asp-controller="Students" asp-action="Import" enctype="multipart/form-data" class="row">
                <div class="form-group col-12 col-md-6 col-lg-6 col-xl-6">
                    <label asp-for="Document">Upload the file</label>
                    <input asp-for="Document" class="form-control-file" type="file" style="width:100%;" />
                </div>
                <hr />
                <div class="form-group button-modal col-12">
                    <input type="submit" value="Start the import process" id="import-submit-button" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Shared/_ChartPartial.cshtml
<!--Load the AJAX API-->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="~/js/chart.js"></script>

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Shared/_ContentPartial.cshtml
@if (!(User.IsInRole("Administrator") && User.IsInRole("Professor") && User.IsInRole("Student")))
{
    
    }

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Shared/_MessagesPartial.cshtml
@if (ViewData["error"] != null)
{
    <div class="alert alert-dismissible alert-danger message-box">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Oh, snap...</strong> @ViewData["error"]
    </div>
}
@if (ViewData["success"] != null)
{
    <div class="alert alert-dismissible alert-success message-box">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Hooray!</strong> @ViewData["success"]
    </div>
}
@if (ViewData["info"] != null)
{
    <div class="alert alert-dismissible alert-info message-box">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>A little note for yourself:</strong> @ViewData["info"].
    </div>
}

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/Shared/_SidebarPartial.cshtml
@if (User.IsInRole("Administrator"))
{
    <div class="col-md-3 col-3 col-xl-3 col-lg-3">
        <div class="w3-sidebar w3-bar-block w3-border-right" id="mySidebar">
            <a asp-controller="Home" asp-action="Dashboard" class="w3-bar-item w3-button" id="dashboard-option">
                <img src="~/images/home-run.svg" style="height: 20px; width: 20px;" />
                Dashboard
            </a>
            <hr />
            <a asp-controller="Professors" asp-action="Index" class="w3-bar-item w3-button">
                <img src="~/images/teacher.svg" style="height: 20px; width: 20px;" />
                Professors
            </a>
            <a asp-controller="Students" asp-action="Index" class="w3-bar-item w3-button">
                <img src="~/images/student.svg" style="height: 20px; width: 20px;" />
                Students
            </a>
            <a asp-controller="Departments" asp-action="Index" class="w3-bar-item w3-button">
                <img src="~/images/svgs/department.svg" style="height: 20px; width: 20px;" />
                Departments
            </a>
            <a asp-controller="Deadlines" asp-action="Index" class="w3-bar-item w3-button">
                <img src="~/images/appointment.svg" style="height: 20px; width: 20px;" />
                Deadlines
            </a>
            <a asp-controller="Options" asp-action="Index" class="w3-bar-item w3-button">
                <img src="~/images/list.svg" style="height: 20px; width: 20px;" />
                Options
            </a>
            <a asp-controller="Options" asp-action="Allocation" class="w3-bar-item w3-button">
                <img src="~/images/cogwheel.svg" style="height: 20px; width: 20px;" />
                Allocation process
            </a>
            <a asp-controller="SystemVariables" asp-action="Edit" class="w3-bar-item w3-button">
                <img src="~/images/settings.svg" style="height: 20px; width: 20px;" />
                Compatibility settings
            </a>
        </div>
    </div>
}
@if (User.IsInRole("Professor"))
{
<div class="col-md-3 col-3 col-xl-3 col-lg-3">
    <div class="w3-sidebar w3-bar-block w3-border-right" id="mySidebar">
        <a asp-controller="Professors" asp-action="Dashboard" class="w3-bar-item w3-button" id="dashboard-option">
            <img src="~/images/home-run.svg" style="height: 20px; width: 20px;" />
            Dashboard
        </a>
        <hr />
        <a asp-controller="PersonalityTestResults" asp-action="Create" class="w3-bar-item w3-button">
            <img src="~/images/register.svg" style="height: 20px; width: 20px;" />
            Personality test
        </a>
        <a asp-controller="UserTags" asp-action="Index" class="w3-bar-item w3-button">
            <img src="~/images/seo-tag.svg" style="height: 20px; width: 20px;" />
            Keywords
        </a>
        <a asp-controller="Deadlines" asp-action="Index" class="w3-bar-item w3-button">
            <img src="~/images/appointment.svg" style="height: 20px; width: 20px;" />
            Deadlines
        </a>
        <a asp-controller="Projects" asp-action="Index" class="w3-bar-item w3-button">
            <img src="~/images/project.svg" style="height: 20px; width: 20px;" />
            Projects
        </a>
        <a asp-controller="Students" asp-action="Suggestions" class="w3-bar-item w3-button">
            <img src="~/images/student.svg" style="height: 20px; width: 20px;" />
            Suggestions
        </a>
        <a asp-controller="Options" asp-action="Index" class="w3-bar-item w3-button">
            <img src="~/images/list.svg" style="height: 20px; width: 20px;" />
            Options
        </a>
        <a asp-controller="Options" asp-action="Sort" class="w3-bar-item w3-button">
            <img src="~/images/project.svg" style="height: 20px; width: 20px;" />
            Sort options
        </a>
    </div>
</div>
}
@if (User.IsInRole("Student"))
{
<div class="col-md-3 col-3 col-xl-3 col-lg-3">
    <div class="w3-sidebar w3-bar-block w3-border-right" id="mySidebar">
        <a asp-controller="Students" asp-action="Dashboard" class="w3-bar-item w3-button" id="dashboard-option">
            <img src="~/images/home-run.svg" style="height: 20px; width: 20px;" />
            Dashboard
        </a>
        <hr />
        <a asp-controller="PersonalityTestResults" asp-action="Create" class="w3-bar-item w3-button">
            <img src="~/images/register.svg" style="height: 20px; width: 20px;" />
            Personality test
        </a>
        <a asp-controller="UserTags" asp-action="Index" class="w3-bar-item w3-button">
            <img src="~/images/seo-tag.svg" style="height: 20px; width: 20px;" />
            Keywords
        </a>
        <a asp-controller="Deadlines" asp-action="Index" class="w3-bar-item w3-button">
            <img src="~/images/appointment.svg" style="height: 20px; width: 20px;" />
            Deadlines
        </a>
        <a asp-controller="Professors" asp-action="Suggestions" class="w3-bar-item w3-button">
            <img src="~/images/teacher.svg" style="height: 20px; width: 20px;" />
            Suggestions
        </a>
        <a asp-controller="Projects" asp-action="Index" class="w3-bar-item w3-button">
            <img src="~/images/project.svg" style="height: 20px; width: 20px;" />
            Projects
        </a>
        <a asp-controller="Options" asp-action="Index" class="w3-bar-item w3-button">
            <img src="~/images/list.svg" style="height: 20px; width: 20px;" />
            Options
        </a>
    </div>
</div>
}