BachelorsDegreeManagement/BachelorsDegreeManagement/Controllers/SystemVariablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BachelorsDegreeManagement.ApplicationLogic.DataModels;
using BachelorsDegreeManagement.DataAccess.Data;
using BachelorsDegreeManagement.ApplicationLogic.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;
using BachelorsDegreeManagement.ApplicationLogic.ViewModels;

namespace BachelorsDegreeManagement.Controllers
{
    [Authorize(Roles="Administrator")]
    public class SystemVariablesController : Controller
    {
        private readonly ISystemVariablesService _variablesService;
        private readonly ILoggerManager _logger;

        public SystemVariablesController(ISystemVariablesService variablesService, ILoggerManager logger)
        {
            _variablesService = variablesService;
            _logger = logger;
        }

        // GET: SystemVariables/Edit
        public IActionResult Edit()
        {
            var model = _variablesService.GetWeights();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UpdateWeightsViewModel model)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    bool updated = _variablesService.UpdateVariables(model);
                    if (updated)
                    {
                        ViewData["success"] = "The weights have been successfully updated";
                    }
                    else
                    {
                        ViewData["error"] = "The weights were not valid. Please try again";
                    }
                }
                catch (DbUpdateConcurrencyException e)
                {
                    _logger.LogError(e.Message);
                }
            }
            return View(model);
        }
    }
}

BachelorsDegreeManagement/BachelorsDegreeManagement/Views/SystemVariables/Edit.cshtml
@model BachelorsDegreeManagement.ApplicationLogic.ViewModels.UpdateWeightsViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-11 col-md-8 col-xl-8 col-lg-8 jumbotron">
        <h4>Edit the weights used in order to compute the compatibility</h4>
        <hr />
        <form asp-action="Edit" class="row justify-content-around">
            <div asp-validation-summary="ModelOnly" class="col-12 text-danger"></div>
            <div class="col-12 col-md-12 col-xl-6 col-lg-6 border-right">
                <h5 class="col-12 text-center">Student/Project weights</h5>
                <div class="form-group col-12">
                    <label asp-for="ProjectPersonalityPercentage" class="control-label"></label>
                    <input asp-for="ProjectPersonalityPercentage" class="form-control project-weights" type="number" step="0.01" />
                    <span asp-validation-for="ProjectPersonalityPercentage" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <label asp-for="ProjectTagsPercentage" class="control-label"></label>
                    <input asp-for="ProjectTagsPercentage" class="form-control project-weights" type="number" step="0.01" />
                    <span asp-validation-for="ProjectTagsPercentage" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <label asp-for="ProjectComplexityPercentage" class="control-label"></label>
                    <input asp-for="ProjectComplexityPercentage" class="form-control project-weights" type="number" step="0.01" />
                    <span asp-validation-for="ProjectComplexityPercentage" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <label asp-for="ProjectSupervisorStylePercentage" class="control-label"></label>
                    <input asp-for="ProjectSupervisorStylePercentage" class="form-control project-weights" type="number" step="0.01" />
                    <span asp-validation-for="ProjectSupervisorStylePercentage" class="text-danger"></span>
                </div>
                <hr />
                <div class="form-group col-12">
                    <label asp-for="ProjectTotalPercentage" class="control-label"></label>
                    <input asp-for="ProjectTotalPercentage" class="form-control project-total valid-total" type="number" step="0.01" disabled />
                    <span asp-validation-for="ProjectTotalPercentage" class="text-danger"></span>
                </div>
            </div>
            <div class="col-12 col-md-12 col-xl-6 col-lg-6">
                <h5 class="col-12 text-center">Student/Professor weights</h5>
                <div class="form-group col-12">
                    <label asp-for="PersonalityPercentage" class="control-label"></label>
                    <input asp-for="PersonalityPercentage" class="form-control professor-weights" type="number" step="0.01" />
                    <span asp-validation-for="PersonalityPercentage" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <label asp-for="TagsPercentage" class="control-label"></label>
                    <input asp-for="TagsPercentage" class="form-control professor-weights" type="number" step="0.01" />
                    <span asp-validation-for="TagsPercentage" class="text-danger"></span>
                </div>
                <div class="form-group col-12 padding-bottom-md-5-7">
                    <label asp-for="SupervisorStylePercentage" class="control-label"></label>
                    <input asp-for="SupervisorStylePercentage" class="form-control professor-weights" type="number" step="0.01" />
                    <span asp-validation-for="SupervisorStylePercentage" class="text-danger"></span>
                </div>
                <hr />
                <div class="form-group col-12">
                    <label asp-for="TotalPercentage" class="control-label"></label>
                    <input asp-for="TotalPercentage" class="form-control professor-total valid-total" type="number" step="0.01" disabled />
                    <span asp-validation-for="TotalPercentage" class="text-danger"></span>
                </div>
            </div>
            <hr />
            <br />
            <div class="form-group col-12">
                <input type="submit" value="Save weights" class="btn btn-primary" id="submit-button" />
            </div>
        </form>
    </div>
    <div class="col-12" id="back-button">
        <a asp-controller="SystemVariables" asp-action="Index"><i class="fas fa-arrow-circle-left"></i> Back to List</a>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}